### ISSUE TITLE
week_01

### ISSUE THREAD

**Issue by liangyepianzhou** [JAVA-01/JAVA-01#10]
＃学号：G20210579020248
＃班级：3班
＃作业和摘要链接：https://github.com/liangyepianzhou/JAVA-01/tree/master/Week_01

**Comment by sunbuer2021** [comment]
＃学号：G20210579030003
＃班级：1班
＃作业和摘要链接：https://github.com/sunbuer2021/JAVA-01/tree/main/Week_01

**Comment by TonySJava** [comment]
＃学号：G20210579020180
＃班级：3班
＃作业和摘要链接：https://github.com/TonySJava/JAVA-01/tree/main/Week_01/week_01_01/JVM

**Comment by GeekUniversity** [comment]
这俩同学作业提交错位置了，不可以在这里交了哦，不然爽爽班主任要打断你的🦵了

**Comment by taoxp** [comment]
#学号: G20210579020101
#班级:2班
#作业&总结链接:https://github.com/taoxp/JAVA-01/tree/main/Week_01
