### ISSUE TITLE
week01

### ISSUE THREAD

**Issue by pomestyle** [JAVA-01/JAVA-01#36]
#学号:G20210579020051
#班级:1班
#作业&总结链接:https://github.com/pomestyle/JAVA-01/tree/main/Week_01

**Comment by pomestyle** [comment]
1

**Comment by melon2624** [comment]
姓名:张鑫
班级：5班
https://github.com/melon2624/javademo/tree/master/src/week1

**Comment by melon2624** [comment]
#学号:G20210579020022
班级：5班
#作业&总结链接:https://github.com/melon2624/javademo/tree/master/src/week1
